"""
Django settings for agrogani_backend project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from corsheaders.defaults import default_headers
from pathlib import Path 
import pymysql
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@btt0sq!crhd=k%1xk83^3j5^4+6v0qa7&v!-56t$oklp=-g4v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console':{
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
    },
}



# ALLOWED_HOSTS = ['34e5-2402-8100-2711-7fd3-4150-960d-bd7a-d49a.ngrok-free.app']
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app','*',]


# Application definition
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
]
# settings.py

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # React dev server
#     # "https://supportive-success-production.up.railway.app",  # Railway frontend (agar ho)
# ]

# # Agar sabhi origins allow karna chahte ho (testing ke liye only!)
# # CORS_ALLOW_ALL_ORIGINS = True


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
     'userprofile',
      'plan',
      'device',
      'crop',
      'labour',
      'expenses',
      'sale',
      'task',
      'shop',
      'reports',
      'advisory',
      'info',
      'rest_framework',
       'adminpanel',
       'adminauth',
    #    'django_extensions',
    'corsheaders',


]

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    

    # 'accounts.middleware.activity_middleware.UserActivityMiddleware',


]

ROOT_URLCONF = 'agrogani_backend.urls'
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agrogani_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_/ 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'agro',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#     }
# }
# SMTP Email for OTP (gmail settings)




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'railway',
        'USER': 'root',
        'PASSWORD': 'wHrfuzKvcJmlyiukEEswuQchEKjAXhCt',
        'HOST': 'switchyard.proxy.rlwy.net',
        'PORT': '41838',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'shivanikush2002@gmail.com'
EMAIL_HOST_PASSWORD =  'txym djer wcuz aihw' 


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
AUTH_USER_MODEL = 'accounts.User'



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),  # Set access token to 7 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=40),  # Set refresh token to 30 days
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# import dj_database_url
import os



SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-secret')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
import os
from dotenv import load_dotenv

# import os

# PORT = os.getenv("PORT", "8000")  # fallback for local

# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config(default='mysql://root:wHrfuzKvcJmlyiukEEswuQchEKjAXhCt@switchyard.proxy.rlwy.net:41838/railway', conn_max_age=600)
# }


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


RAZORPAY_KEY_ID = "rzp_test_Wt9uDBVijEMhhU"
RAZORPAY_KEY_SECRET = "TkpZXRLwI2vqBg8put1DBJCQ"


from decouple import config
WEATHER_API_KEY="be5a3a3aad7ded2bde2e15e8895c7cf7"


# settings.py के नीचे जोड़ें (DEBUG=True के बाद)

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True  # सभी origins को allow करें (development के लिए)
    CORS_ALLOW_CREDENTIALS = True   # JWT/cookies के लिए जरूरी
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "https://supportive-success-production.up.railway.app",

        "https://agro1.netlify.app/",
       
    ]
    CORS_ALLOW_CREDENTIALS = True

# settings.py


