# Generated by Django 4.2.23 on 2025-06-29 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('expense_type', models.CharField(choices=[('labour', 'Labour Payment'), ('fertilizer', 'Fertilizer & Pesticide Invoice'), ('seed', 'Seed Invoice'), ('equipment', 'Equipment Expense')], max_length=20)),
                ('date', models.DateField()),
                ('paying_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank')], max_length=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('bill_photo', models.ImageField(blank=True, null=True, upload_to='bills/')),
                ('bill_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('labour_name', models.CharField(blank=True, max_length=100, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('seed_name', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
