# Generated by Django 4.2.23 on 2025-07-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('advance', 'Advance'), ('regular', 'Regular')], max_length=10),
        ),
    ]
