# Generated by Django 5.2.4 on 2025-07-27 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_fertilizershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 27, 13, 7, 17, 893918, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
