# Generated by Django 4.2.23 on 2025-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_razorpaylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
