# Generated by Django 5.2.5 on 2025-08-24 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='extra_info',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='accessed_at',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='was_accessed',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='icon_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
