# Generated by Django 5.2.4 on 2025-07-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='was_accessed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
