# Generated by Django 4.2.23 on 2025-07-14 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Irrigation', 'Irrigation'), ('Fertilization', 'Fertilization'), ('Harvesting', 'Harvesting'), ('Planting', 'Planting'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=50)),
                ('crop', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('reminder', models.CharField(default='At time of task', max_length=50)),
                ('assigned_to', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('weather_sensitive', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('repeat_type', models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], default='None', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
