# Generated by Django 4.2.23 on 2025-07-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_recurring',
        ),
    ]
