# Generated by Django 4.2.23 on 2025-07-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='repeat_type',
        ),
    ]
