# Generated by Django 5.2.5 on 2025-09-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_sync_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='task_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
