# Generated by Django 5.2.5 on 2025-09-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'About Us'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('contact', 'Contact Us')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='HTML content allowed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
