# Generated by Django 5.2.5 on 2025-09-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('about', 'About Us'), ('contact', 'Contact Us')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
