# Generated by Django 4.2.23 on 2025-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_quicksale_crop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksale',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
