# Generated by Django 5.2.4 on 2025-08-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_quicksale_crop_name'),
        ('shop', '0002_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedsale',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.buyer'),
        ),
    ]
